version: '3.3'

services:
  db:
    image: postgres:13-alpine
    ports: [ '5432:5432' ]
    restart: always
    environment:
      - DEBUG=false
      - POSTGRES_USER=manfred
      - POSTGRES_PASSWORD=manfred
      - POSTGRES_DB=manfred
    volumes:
      - data:/var/lib/postgresql/data

  apigo:
    build: "."
    ports:
      - "8080"

  nginx:
    build: "./docker/nginx"
    ports:
      - "80:80"
    depends_on:
      - "apigo"

volumes:
  data:

